#include "LQR_VMC.h"
#include "arm_math.h"
#include <math.h>

void lqr_k( double L0, double K[ 12 ] ) {
    double t2;
    double t3;
    /*     This function was generated by the Symbolic Math Toolbox version 9.2.
     */
    /*     20-Dec-2023 11:13:07 */
    t2 = L0 * L0;
    t3 = L0 * L0 * L0;

	t2 = L0 * L0;
  t3 = L0 * L0 * L0;
	
	


//  K[0] = ((L0 * -772.54600359509425 + t2 * 636.26556711935643) -
//          t3 * 389.49820286639391) -
//         65.516815413061991;
//  K[1] = ((L0 * 68.096807941533314 - t2 * 197.6919956347451) +
//          t3 * 178.64157843741489) +
//         10.81382181357864;
//  K[2] = ((L0 * -96.207795891542958 - t2 * 149.64588812760749) +
//          t3 * 116.17253592878561) -
//         12.20764850678199;
//  K[3] = ((L0 * 2.9947803364145908 + t2 * 0.15788537081777029) -
//          t3 * 4.8262276086568594) +
//         2.925767633098165;
//  K[4] = ((L0 * -2.6670969666009068 + t2 * 1.85788724772626) +
//          t3 * 1.172727418120302) -
//         27.395745267092568;
//  K[5] = ((L0 * -4.9376671118675377 - t2 * 6.3733077474769928) +
//          t3 * 14.134492411489161) +
//         3.9948719744533641;
//  K[6] = ((L0 * -3.6666969842609252 - t2 * 45.221554467512881) +
//          t3 * 57.799583081089892) -
//         84.95210986809191;
//  K[7] = ((L0 * -16.2423388777015 - t2 * 12.658892941477671) +
//          t3 * 34.60140929220151) +
//         12.23888290623924;
//  K[8] = ((L0 * -273.71396539763128 + t2 * 418.33546539913948) -
//          t3 * 279.17103536445609) +
//         107.0981382717641;
//  K[9] = ((L0 * 48.403990806155022 - t2 * 93.9673330661182) +
//          t3 * 71.442670732665945) +
//         120.2677070469459;
//  K[10] = ((L0 * -19.408573170294169 + t2 * 33.158360264553387) -
//           t3 * 24.972888802537419) +
//          11.830620223124519;
//  K[11] = ((L0 * -2.6488559055659961 + t2 * 12.652149602764959) -
//           t3 * 14.343564151899789) +
//          3.8585470685837309;

//1000 100 400 3000 25000 1

  K[0] = ((L0 * -736.93653113032553 + t2 * 555.89790231801931) -
          t3 * 318.47587448140177) -
         74.652767567858277;
  K[1] = ((L0 * 57.088067848759543 - t2 * 173.8273021426989) +
          t3 * 158.532051183351) +
         13.17360980014247;
  K[2] = ((L0 * -96.102849148047525 - t2 * 149.989008947167) +
          t3 * 116.502175966964) -
         12.27166594887205;
  K[3] = ((L0 * 3.356374721714432 - t2 * 0.80675816440378623) -
          t3 * 3.92121777993562) +
         2.8765203064305669;
  K[4] = ((L0 * -2.0260567334912789 - t2 * 0.0768569329653259) +
          t3 * 3.1572340322012979) -
         27.469635377992521;
  K[5] = ((L0 * -3.2768036393747062 - t2 * 11.307697984187239) +
          t3 * 19.15349036265912) +
         3.7966428590466692;
  K[6] = ((L0 * 3.16206573914299 - t2 * 64.0257078726192) +
          t3 * 76.248859914384838) -
         85.987251044021008;
  K[7] = ((L0 * -11.71445999113657 - t2 * 26.36789654679216) +
          t3 * 48.688013749071253) +
         11.720977115590831;
  K[8] = ((L0 * -276.10301402652721 + t2 * 421.190770735406) -
          t3 * 279.94887011872731) +
         107.8172200166526;
  K[9] = ((L0 * 49.00520707247081 - t2 * 94.796933559530316) +
          t3 * 71.718348512209687) +
         120.1225879413155;
  K[10] = ((L0 * -19.9179437432334 + t2 * 34.659440140234949) -
           t3 * 26.499950540055991) +
          11.89594515367515;
  K[11] = ((L0 * -2.95509028352256 + t2 * 13.578675068241431) -
           t3 * 15.29800990041895) +
          3.894011720219869;

}


void VM_cal(double F0, double Tp, double phi1, double phi4, double *Tp1,
            double *Tp2)
{
  double A0;
  double B0;
  double C0;
  double XB_tmp;
  double XD;
  double YB_tmp;
  double YD;
  double lBD;
  double phi2;
  double phi3;
  YD = 0.15 * sin(phi4);
  YB_tmp = 0.15 * sin(phi1);
  XD = 0.15 * cos(phi4) + 0.15;
  XB_tmp = 0.15 * cos(phi1);
  C0 = XD - XB_tmp;
  B0 = YD - YB_tmp;
  lBD = sqrt(C0 * C0 + B0 * B0);
  A0 = 0.54 * C0;
  B0 *= 0.54;
  C0 = (lBD * lBD + 0.0729) - 0.0729;
  phi2 = 2.0 * atan2(B0 + sqrt((A0 * A0 + B0 * B0) - C0 * C0), A0 + C0);
  C0 = 0.27 * cos(phi2);
  lBD = 0.27 * sin(phi2);
  phi3 = atan2((YB_tmp - YD) + lBD, (XB_tmp - XD) + C0);
  B0 = XB_tmp + C0;
  C0 = YB_tmp + lBD;
  XD = sqrt((B0 - 0.075) * (B0 - 0.075) + C0 * C0);
  C0 = atan2(C0, B0 - 0.075);
  lBD = sin(phi1 - phi2);
  A0 = sin(phi3 - phi2);
  YD = sin(phi3 - phi4);
  B0 = C0 - phi3;
  C0 -= phi2;
  *Tp1 = 0.15 * sin(B0) * lBD / A0 * F0 + 0.15 * cos(B0) * lBD / XD * A0 * Tp;
  *Tp2 = 0.15 * sin(C0) * YD / A0 * F0 + 0.15 * cos(C0) * YD / XD * A0 * Tp;
}

void get_legparam(double phi1, double phi4, double *L0, double *phi0)
{
  double A0;
  double B0;
  double C0;
  double XB_tmp;
  double YB_tmp;
  double lBD;
  YB_tmp = 0.15 * sin(phi1);
  XB_tmp = 0.15 * cos(phi1);
  C0 = (0.15 * cos(phi4) + 0.15) - XB_tmp;
  B0 = 0.15 * sin(phi4) - YB_tmp;
  lBD = sqrt(C0 * C0 + B0 * B0);
  A0 = 0.54 * C0;
  B0 *= 0.54;
  C0 = (lBD * lBD + 0.0729) - 0.0729;
  C0 = 2.0 * atan2(B0 + sqrt((A0 * A0 + B0 * B0) - C0 * C0), A0 + C0);
  B0 = XB_tmp + 0.27 * cos(C0);
  C0 = YB_tmp + 0.27 * sin(C0);
  *L0 = sqrt((B0 - 0.075) * (B0 - 0.075) + C0 * C0);
  *phi0 = atan2(C0, B0 - 0.075);
}

double get_dphi0(double phi_1, double phi_4, double d_phi1, double d_phi4)
{
  double a;
  double a_tmp;
  double a_tmp_tmp;
  double b_a;
  double b_a_tmp;
  double b_a_tmp_tmp;
  double b_d_phi0_tmp;
  double b_d_phi0_tmp_tmp;
  double c_a;
  double c_a_tmp;
  double c_a_tmp_tmp;
  double c_d_phi0_tmp;
  double c_d_phi0_tmp_tmp;
  double d_a;
  double d_a_tmp;
  double d_a_tmp_tmp;
  double d_d_phi0_tmp;
  double d_d_phi0_tmp_tmp;
  double d_phi0_tmp;
  double d_phi0_tmp_tmp;
  double e_a;
  double e_a_tmp;
  double f_a;
  double f_a_tmp;
  double g_a;
  double h_a;
  double i_a;
  d_phi0_tmp_tmp = cos(phi_1);
  b_d_phi0_tmp_tmp = sin(phi_1);
  c_d_phi0_tmp_tmp = cos(phi_4);
  d_d_phi0_tmp_tmp = sin(phi_4);
  a_tmp_tmp = 0.15 * b_d_phi0_tmp_tmp;
  a_tmp = a_tmp_tmp - 0.15 * d_d_phi0_tmp_tmp;
  b_a_tmp_tmp = 0.15 * d_phi0_tmp_tmp;
  b_a_tmp = (0.15 - b_a_tmp_tmp) + 0.15 * c_d_phi0_tmp_tmp;
  c_a_tmp_tmp = a_tmp * a_tmp;
  d_a_tmp_tmp = b_a_tmp * b_a_tmp;
  c_a_tmp = ((c_a_tmp_tmp + d_a_tmp_tmp) + 0.0729) - 0.0729;
  d_a_tmp = c_a_tmp + 0.54 * b_a_tmp;
  e_a_tmp = 0.54 * a_tmp;
  f_a_tmp = 0.2916 * c_a_tmp_tmp;
  c_a_tmp_tmp = 0.2916 * d_a_tmp_tmp;
  d_a_tmp_tmp = sqrt((f_a_tmp - c_a_tmp * c_a_tmp) + c_a_tmp_tmp) - e_a_tmp;
  a = sqrt((f_a_tmp - c_a_tmp * c_a_tmp) + c_a_tmp_tmp) - e_a_tmp;
  b_a = (0.27 *
             cos(2.0 * atan((sqrt((f_a_tmp - c_a_tmp * c_a_tmp) + c_a_tmp_tmp) -
                             e_a_tmp) /
                            d_a_tmp)) -
         0.075) +
        b_a_tmp_tmp;
  c_a =
      0.27 * sin(2.0 * atan((sqrt((f_a_tmp - c_a_tmp * c_a_tmp) + c_a_tmp_tmp) -
                             e_a_tmp) /
                            d_a_tmp)) +
      a_tmp_tmp;
  d_a = (0.27 *
             cos(2.0 * atan((sqrt((f_a_tmp - c_a_tmp * c_a_tmp) + c_a_tmp_tmp) -
                             e_a_tmp) /
                            d_a_tmp)) -
         0.075) +
        b_a_tmp_tmp;
  e_a = sqrt((f_a_tmp - c_a_tmp * c_a_tmp) + c_a_tmp_tmp) - e_a_tmp;
  f_a = sqrt((f_a_tmp - c_a_tmp * c_a_tmp) + c_a_tmp_tmp) - e_a_tmp;
  g_a = (0.27 *
             cos(2.0 * atan((sqrt((f_a_tmp - c_a_tmp * c_a_tmp) + c_a_tmp_tmp) -
                             e_a_tmp) /
                            d_a_tmp)) -
         0.075) +
        b_a_tmp_tmp;
  h_a =
      0.27 * sin(2.0 * atan((sqrt((f_a_tmp - c_a_tmp * c_a_tmp) + c_a_tmp_tmp) -
                             e_a_tmp) /
                            d_a_tmp)) +
      a_tmp_tmp;
  i_a = (0.27 *
             cos(2.0 * atan((sqrt((f_a_tmp - c_a_tmp * c_a_tmp) + c_a_tmp_tmp) -
                             e_a_tmp) /
                            d_a_tmp)) -
         0.075) +
        b_a_tmp_tmp;
  d_phi0_tmp = 0.08748 * d_phi0_tmp_tmp * a_tmp;
  b_d_phi0_tmp = 0.08748 * b_d_phi0_tmp_tmp * b_a_tmp;
  c_d_phi0_tmp = 0.08748 * c_d_phi0_tmp_tmp * a_tmp;
  d_d_phi0_tmp = 0.08748 * d_d_phi0_tmp_tmp * b_a_tmp;
  return d_phi1 *
             ((0.15 * d_phi0_tmp_tmp +
               0.54 *
                   cos(2.0 *
                       atan((sqrt((f_a_tmp - c_a_tmp * c_a_tmp) + c_a_tmp_tmp) -
                             e_a_tmp) /
                            d_a_tmp)) *
                   ((((d_phi0_tmp - 2.0 *
                                        (0.3 * d_phi0_tmp_tmp * a_tmp +
                                         0.3 * b_d_phi0_tmp_tmp * b_a_tmp) *
                                        c_a_tmp) +
                      b_d_phi0_tmp) /
                         (2.0 *
                          sqrt((f_a_tmp - c_a_tmp * c_a_tmp) + c_a_tmp_tmp)) -
                     0.081 * d_phi0_tmp_tmp) /
                        d_a_tmp -
                    (sqrt((f_a_tmp - c_a_tmp * c_a_tmp) + c_a_tmp_tmp) -
                     e_a_tmp) *
                        ((0.081 * b_d_phi0_tmp_tmp +
                          0.3 * cos(phi_1) *
                              (0.15 * sin(phi_1) - 0.15 * sin(phi_4))) +
                         0.3 * sin(phi_1) *
                             ((0.15 - 0.15 * cos(phi_1)) + 0.15 * cos(phi_4))) /
                        (d_a_tmp * d_a_tmp)) /
                   (d_a_tmp_tmp * d_a_tmp_tmp / (d_a_tmp * d_a_tmp) + 1.0)) /
                  ((0.27 * cos(2.0 * atan((sqrt((f_a_tmp - c_a_tmp * c_a_tmp) +
                                                c_a_tmp_tmp) -
                                           e_a_tmp) /
                                          d_a_tmp)) -
                    0.075) +
                   b_a_tmp_tmp) +
              (0.27 * sin(2.0 * atan((sqrt((f_a_tmp - c_a_tmp * c_a_tmp) +
                                           c_a_tmp_tmp) -
                                      e_a_tmp) /
                                     d_a_tmp)) +
               a_tmp_tmp) *
                  (a_tmp_tmp +
                   0.54 *
                       sin(2.0 * atan((sqrt((f_a_tmp - c_a_tmp * c_a_tmp) +
                                            c_a_tmp_tmp) -
                                       e_a_tmp) /
                                      d_a_tmp)) *
                       ((((d_phi0_tmp -
                           2.0 *
                               (0.3 * cos(phi_1) *
                                    (0.15 * sin(phi_1) - 0.15 * sin(phi_4)) +
                                0.3 * sin(phi_1) *
                                    ((0.15 - 0.15 * cos(phi_1)) +
                                     0.15 * cos(phi_4))) *
                               (((a_tmp * a_tmp + b_a_tmp * b_a_tmp) + 0.0729) -
                                0.0729)) +
                          b_d_phi0_tmp) /
                             (2.0 * sqrt((f_a_tmp - c_a_tmp * c_a_tmp) +
                                         c_a_tmp_tmp)) -
                         0.081 * cos(phi_1)) /
                            d_a_tmp -
                        (sqrt((f_a_tmp - c_a_tmp * c_a_tmp) + c_a_tmp_tmp) -
                         e_a_tmp) *
                            ((0.081 * sin(phi_1) +
                              0.3 * cos(phi_1) *
                                  (0.15 * sin(phi_1) - 0.15 * sin(phi_4))) +
                             0.3 * sin(phi_1) *
                                 ((0.15 - 0.15 * cos(phi_1)) +
                                  0.15 * cos(phi_4))) /
                            (d_a_tmp * d_a_tmp)) /
                       (a * a / (d_a_tmp * d_a_tmp) + 1.0)) /
                  (b_a * b_a)) /
             (c_a * c_a / (d_a * d_a) + 1.0) -
         d_phi4 *
             (0.54 *
                  cos(2.0 *
                      atan((sqrt((f_a_tmp - c_a_tmp * c_a_tmp) + c_a_tmp_tmp) -
                            e_a_tmp) /
                           d_a_tmp)) *
                  ((((c_d_phi0_tmp - 2.0 *
                                         (0.3 * c_d_phi0_tmp_tmp * a_tmp +
                                          0.3 * d_d_phi0_tmp_tmp * b_a_tmp) *
                                         c_a_tmp) +
                     d_d_phi0_tmp) /
                        (2.0 *
                         sqrt((f_a_tmp - c_a_tmp * c_a_tmp) + c_a_tmp_tmp)) -
                    0.081 * c_d_phi0_tmp_tmp) /
                       d_a_tmp -
                   (sqrt((f_a_tmp - c_a_tmp * c_a_tmp) + c_a_tmp_tmp) -
                    e_a_tmp) *
                       ((0.081 * d_d_phi0_tmp_tmp +
                         0.3 * cos(phi_4) *
                             (0.15 * sin(phi_1) - 0.15 * sin(phi_4))) +
                        0.3 * sin(phi_4) *
                            ((0.15 - 0.15 * cos(phi_1)) + 0.15 * cos(phi_4))) /
                       (d_a_tmp * d_a_tmp)) /
                  ((e_a * e_a / (d_a_tmp * d_a_tmp) + 1.0) *
                   ((0.27 * cos(2.0 * atan((sqrt((f_a_tmp - c_a_tmp * c_a_tmp) +
                                                 c_a_tmp_tmp) -
                                            e_a_tmp) /
                                           d_a_tmp)) -
                     0.075) +
                    b_a_tmp_tmp)) +
              0.54 *
                  sin(2.0 *
                      atan((sqrt((f_a_tmp - c_a_tmp * c_a_tmp) + c_a_tmp_tmp) -
                            e_a_tmp) /
                           d_a_tmp)) *
                  (0.27 * sin(2.0 * atan((sqrt((f_a_tmp - c_a_tmp * c_a_tmp) +
                                               c_a_tmp_tmp) -
                                          e_a_tmp) /
                                         d_a_tmp)) +
                   a_tmp_tmp) *
                  ((((c_d_phi0_tmp -
                      2.0 *
                          (0.3 * cos(phi_4) *
                               (0.15 * sin(phi_1) - 0.15 * sin(phi_4)) +
                           0.3 * sin(phi_4) *
                               ((0.15 - 0.15 * cos(phi_1)) +
                                0.15 * cos(phi_4))) *
                          (((a_tmp * a_tmp + b_a_tmp * b_a_tmp) + 0.0729) -
                           0.0729)) +
                     d_d_phi0_tmp) /
                        (2.0 *
                         sqrt((f_a_tmp - c_a_tmp * c_a_tmp) + c_a_tmp_tmp)) -
                    0.081 * cos(phi_4)) /
                       d_a_tmp -
                   (sqrt((f_a_tmp - c_a_tmp * c_a_tmp) + c_a_tmp_tmp) -
                    e_a_tmp) *
                       ((0.081 * sin(phi_4) +
                         0.3 * cos(phi_4) *
                             (0.15 * sin(phi_1) - 0.15 * sin(phi_4))) +
                        0.3 * sin(phi_4) *
                            ((0.15 - 0.15 * cos(phi_1)) + 0.15 * cos(phi_4))) /
                       (d_a_tmp * d_a_tmp)) /
                  ((f_a * f_a / (d_a_tmp * d_a_tmp) + 1.0) * (g_a * g_a))) /
             (h_a * h_a / (i_a * i_a) + 1.0);
}

