/*
 * File: lqr_k.c
 *
 * MATLAB Coder version            : 5.5
 * C/C++ source code generated on  : 28-Mar-2026 16:01:54
 */

/* Include Files */
#include "lqr_k.h"
#include "rt_nonfinite.h"
#include "rt_nonfinite.h"
#include <math.h>

/* Function Declarations */
static double rt_powd_snf(double u0, double u1);

/* Function Definitions */
/*
 * Arguments    : double u0
 *                double u1
 * Return Type  : double
 */
static double rt_powd_snf(double u0, double u1)
{
  double y;
  if (rtIsNaN(u0) || rtIsNaN(u1)) {
    y = rtNaN;
  } else {
    double d;
    double d1;
    d = fabs(u0);
    d1 = fabs(u1);
    if (rtIsInf(u1)) {
      if (d == 1.0) {
        y = 1.0;
      } else if (d > 1.0) {
        if (u1 > 0.0) {
          y = rtInf;
        } else {
          y = 0.0;
        }
      } else if (u1 > 0.0) {
        y = 0.0;
      } else {
        y = rtInf;
      }
    } else if (d1 == 0.0) {
      y = 1.0;
    } else if (d1 == 1.0) {
      if (u1 > 0.0) {
        y = u0;
      } else {
        y = 1.0 / u0;
      }
    } else if (u1 == 2.0) {
      y = u0 * u0;
    } else if ((u1 == 0.5) && (u0 >= 0.0)) {
      y = sqrt(u0);
    } else if ((u0 < 0.0) && (u1 > floor(u1))) {
      y = rtNaN;
    } else {
      y = pow(u0, u1);
    }
  }
  return y;
}

/*
 * LQR_K
 *     K = LQR_K(L0)
 *
 * Arguments    : double L0
 *                double K[12]
 * Return Type  : void
 */
void lqr_k(double L0, double K[12])
{
  double t2;
  double t3;
  /*     This function was generated by the Symbolic Math Toolbox version 9.2.
   */
  /*     28-Mar-2026 15:54:13 */
  t2 = L0 * L0;
  t3 = rt_powd_snf(L0, 3.0);
  K[0] = ((L0 * -736.93653113032553 + t2 * 555.89790231801931) -
          t3 * 318.47587448140177) -
         74.652767567858277;
  K[1] = ((L0 * 57.088067848759543 - t2 * 173.8273021426989) +
          t3 * 158.532051183351) +
         13.17360980014247;
  K[2] = ((L0 * -96.102849148047525 - t2 * 149.989008947167) +
          t3 * 116.502175966964) -
         12.27166594887205;
  K[3] = ((L0 * 3.356374721714432 - t2 * 0.80675816440378623) -
          t3 * 3.92121777993562) +
         2.8765203064305669;
  K[4] = ((L0 * -2.0260567334912789 - t2 * 0.0768569329653259) +
          t3 * 3.1572340322012979) -
         27.469635377992521;
  K[5] = ((L0 * -3.2768036393747062 - t2 * 11.307697984187239) +
          t3 * 19.15349036265912) +
         3.7966428590466692;
  K[6] = ((L0 * 3.16206573914299 - t2 * 64.0257078726192) +
          t3 * 76.248859914384838) -
         85.987251044021008;
  K[7] = ((L0 * -11.71445999113657 - t2 * 26.36789654679216) +
          t3 * 48.688013749071253) +
         11.720977115590831;
  K[8] = ((L0 * -276.10301402652721 + t2 * 421.190770735406) -
          t3 * 279.94887011872731) +
         107.8172200166526;
  K[9] = ((L0 * 49.00520707247081 - t2 * 94.796933559530316) +
          t3 * 71.718348512209687) +
         120.1225879413155;
  K[10] = ((L0 * -19.9179437432334 + t2 * 34.659440140234949) -
           t3 * 26.499950540055991) +
          11.89594515367515;
  K[11] = ((L0 * -2.95509028352256 + t2 * 13.578675068241431) -
           t3 * 15.29800990041895) +
          3.894011720219869;
}

/*
 * File trailer for lqr_k.c
 *
 * [EOF]
 */
